spring:
  datasource-mysql:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: H2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  defer-datasource-initialization: true



  data:
    mongodb:
      uri: mongodb://localhost:27019/admin
      host: localhost
      port: 27019
      database: MWT_MARKET
      username: username
      password: password

  cloud:
    aws:
      credentials:
        access-key: 나는야엑세스키
        secret-key: 나는야시크릿키
      region:
        static: ap-northeast-2

server:
  servlet:
    context-path: /api/v1

jwt:
  secret-key: 나는야시크릿키
  access-token-expire-time: 111
  refresh-token-expire-time: 111
  issuer: 나는야발급자

remote-server:
  front:
    url:
  gateway:
    url:
