spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update

  data:
    mongodb:
      uri: mongodb://localhost:27019/admin
      host: localhost
      port: 27019
      database: MWT_MARKET
      username: username
      password: password

server:
  servlet:
    context-path: /api/v1

jwt:
  secret-key: 나는야시크릿키
  access-token-expire-time: 111
  refresh-token-expire-time: 111
  issuer: 나는야발급자

remote-server:
  front:
    url:
  gateway:
    url: