name: reviewdog
on:
  pull_request:
    branches: [ main, develop ]
jobs:
  build_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: application.yml
        run: |
          mkdir -p src/main/resources
          touch ./src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_LOCAL }}" > ./src/main/resources/application.yml
          cat ./src/main/resources/application.yml
          rm ./src/main/resources/data.sql
      - name: Run chmod to make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
        with:
          arguments: build
